### ISSUE TITLE
Error in ratematrixMCMC

### ISSUE THREAD

**Issue by drossoni** [Caetanods/ratematrix#35]
Hi Daniel, 
I am applying the function ratematrixMCMC on a data.frame (with 57 species and 2 traits), and on a phylogeny (“simmap” class with 8 regimes). The function is reporting the following error:

Error in chol.default(Rs1 + Rs2) : the leading minor of order 1 is not positive definite. 

Thanks a lot for your attention.

**Comment by Caetanods** [comment]
Hello 'drossoni',

The error is a issue that I am working right now. I implemented the pruning algorithm (applied to make the computations faster) for the case of 2 rate regimes, mainly because this is the case for my empirical data and simulations. I need to extend this to fit more rate regimes. I will work on it and return to you with a fix as soon as possible.

That being said, it is good to check the distribution of your regimes across the branches of the phylogenetic tree. When a regime is restricted to very few species it can be difficult to estimate the parameters or the posterior distribution might be very wide (i.e., a lot of uncertainty).

Thanks for your message!

**Comment by Caetanods** [comment]
Ok. Just implemented the fix for the package. Should work now. Please see bellow a script with a short example.

```
devtools::install_github("Caetanods/ratematrix")
library( ratematrix )
library( phytools )

## Data simulation.
tree <- pbtree(n=57)
trait <- c(rep(c("A","B","C","D","E","F","G","H"), each = 7),"H")
names(trait) <- tree$tip.label
## This 'simmap' will look terrible, but this is just a quick example.
map <- make.simmap(tree, x=trait, model="ARD")

## The evolutionary rate matrices for each regime.
R1 <- rbind(c(1,0.5), c(0.5,1))
R2 <- rbind(c(2,1), c(1,2))
R3 <- rbind(c(1,0), c(0,1))
R4 <- rbind(c(2,0), c(0,2))
R5 <- rbind(c(1,0.5), c(0.5,1))
R6 <- rbind(c(2,1), c(1,2))
R7 <- rbind(c(1,0), c(0,1))
R8 <- rbind(c(1,0.5), c(0.5,1))
ll <- list("A"=R1, "B"=R2, "C"=R3, "D"=R4, "E"=R5, "F"=R6, "G"=R7, "H"=R8)
root <- c(1,1)

## The data.
data <- sim.corrs(tree=map, vcv=ll, anc=root)

## Start the MCMC with default parameters.
## Note that this chain is very short. Need more for convergence.
mcmc_handle <- ratematrixMCMC(data=data, phy=map, prior="uniform", gen=1000, chunk=100, outname="example")

## Read the result.
mcmc <- readMCMC(handle=mcmc_handle, thin=10)

## Plot the result. You will need many colors.
## These plots will also look bad.
cols <- c("red","blue","green","pink","gray","purple","yellow","cyan")
plotRatematrix(mcmc, colors=cols)
plotRootValue(mcmc)

## Make test:
## Here the tests are made with all pairwise combinations of regimes. So the number of combinations is large.
## The idea is that everything that is larger than 0.05 can be collapsed down to a single distribution.
testRatematrix(mcmc, par="all")
testRatematrix(mcmc, par="correlation")
testRatematrix(mcmc, par="rates")
```
